### ISSUE TITLE
Redeploy 

### ISSUE THREAD

**Issue by iahmedani** [kobotoolbox/formpack#123]
Dear Team,

I have been using kobo toolbox on my server using kobo docker, here are few errors which I have observed.

> When we made changes in deployed form and again redeploy, it shows successfully deployed but in the project (kobocat) remains the previous version. 

> Form designed on xls and deployed, it changes all field in required except group and notes, which shouldn't be, as in ODK the questions declared true in required column are mandatory.

> kobo from doesn't support advanced conditions in skips as well as in validation

Please do something.

Regards,
Imran Ahmedani

**Comment by iahmedani** [comment]
the same issue is iterated over here as well 
[Issue](http://support.kobotoolbox.org/customer/portal/questions/16372060-edit-form-redeploy-but-no-change-happen-to-the-form)

**Comment by esmail** [comment]
@iahmedani, this is not an issue with `formpack`, which handles tasks relating to data exports. It was a bug in KPI that was closed yesterday, tracked here: https://github.com/kobotoolbox/kpi/issues/1156
