### ISSUE TITLE
Multi-section csv exports aren't supported

### ISSUE THREAD

**Issue by starsep** [kobotoolbox/formpack#131]
Multi-section csv exports aren't supported. https://`KOBOCAT_HOSTNAME`/`USERNAME`/reports/`FORM_STRING_ID`/export.csv returns csv with only first section. 

Code is at https://github.com/kobotoolbox/formpack/blob/master/src/formpack/reporting/export.py#L378
``` python
def to_csv(self, submissions, sep=";", quote='"'):
        # [ ... ]
        sections = list(self.labels.items())

        # if len(sections) > 1:
        #     raise RuntimeError("CSV export does not support repeatable groups")
        # [ ... ]
        section, labels = sections[0]
```
Any plans to implement/fix that?

EDIT: git blame showed that @dorey or @ksamuel might know the answer

**Comment by dorey** [comment]
Is there an example of representation of those kinds of nested structures in CSV?

Would a JSON representation suffice for your needs?

**Comment by starsep** [comment]
kobocat data api (`https://{HOSTNAME}/api/v1/data/{FORM_ID}.csv`) generates such CSVs.
Code is at https://github.com/kobotoolbox/kobocat/blob/master/onadata/apps/api/viewsets/data_viewset.py
I don't exactly understand what is going on there, but the CSV result is made of horizontally concatenated CSV representations of sections (with appropriate indexing in headers).
The problem with data api is that it is not reliable with larger forms.

For now XLSXs/JSONs are fine, but having reliable CSV export would be nice.
