### ISSUE TITLE
Excel export stores non-empty text in blank cells

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/formpack#137]
When exporting to XLS any cell that doesn't contain data still stores some blank value (like blank space) instead of being completely empty. This balloons the file needlessly and makes using large XLS files more difficult. 

![image](https://user-images.githubusercontent.com/673511/32349534-cdc27734-bfed-11e7-8872-768437055c95.png)

Possibly related to #44

**Comment by jnm** [comment]
This seems not to be a problem in LibreOffice:
![image](https://user-images.githubusercontent.com/2085013/33908825-a230b98a-df57-11e7-8452-81292a2c58b6.png)

However, also in LibO, when saving this sheet:
![image](https://user-images.githubusercontent.com/2085013/33908871-c5d0a4ae-df57-11e7-97aa-c58a8601523e.png)
I end up with this XML, where the blank cells are entirely omitted:
```xml
<sheetData>
	<row r="1" customFormat="false" ht="12.8" hidden="false" customHeight="false" outlineLevel="0" collapsed="false">
		<c r="A1" s="0" t="s">
			<v>0</v>
		</c>
	</row>
	<row r="3" customFormat="false" ht="12.8" hidden="false" customHeight="false" outlineLevel="0" collapsed="false">
		<c r="A3" s="0" t="s">
			<v>1</v>
		</c>
	</row>
</sheetData>
```
...but the XML for the export shown in the first screenshot contains elements for the blank cells, e.g.:
```xml
<c r="C6" t="inlineStr">
	<is>
		<t/>
	</is>
</c>
```

**Comment by joshuaberetta** [comment]
@tinok this doesn't seem to still be the case (or at least I'm battling to reproduce it), can you confirm if you are still seeing this issue?
