### ISSUE TITLE
Labeled export fails if option label is blank

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/formpack#139]
Export fails if an option label for the chosen language of a labeled XLS export is blank.

Instead of the missing label, formpack should include the XML name. (Same should be done if the question label is missing.)

For example, below image shows that the response option has no label:
![image](https://user-images.githubusercontent.com/673511/32387308-70ea7432-c09a-11e7-9a98-9ba734f4399a.png)

**Comment by jnm** [comment]
Still a problem:
https://kf.master.kbtdev.org/#/forms/auUY6tEb6WFeqTfZXvjjTm/data/downloads (try non-English languages and autoreport)
http://sentry.kbtdev.org/kobo/kpi/issues/1624/
http://sentry.kbtdev.org/kobo/kpi/issues/3870/

**Comment by joshuaberetta** [comment]
This appears to no longer be the case — XML names are used if a translation is unavailable.
