### ISSUE TITLE
Columns for or_other are missing from exports

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/formpack#140]
Questions with `or_other` (e.g. `select_multiple   myanmar_orgs_kap or_other`) are missing the /other column (one of the boolean columns) and the _other columns (the text question added after the usual output). 

XLSForm:

type | name | label
-- | -- | --
select_multiple voting_preference or_other | voting_pref | Which party do you normally vote for in elections?

Expected output in kpi exports (after other select_multiple columns):

voting_pref/other | voting_pref_other
-- | --
1 | Green Party
1 | Libertarians 
0 | 
0 | 
1 | Pirate party

To do: 
Test that or_other outputs work with select_one questions
Test that or_other outputs work with select_multiple questions (as in above example)

**Comment by Kalyan-Lama** [comment]
Community: https://community.kobotoolbox.org/t/allow-export-of-or-other-columns-before-retiring-legacy-xls-export/17342
