### ISSUE TITLE
Columns in exports are out of sequence

### ISSUE THREAD

**Issue by noliveleger** [kobotoolbox/formpack#159]
This bug is related to this issue https://github.com/kobotoolbox/kpi/issues/1570

**Comment by jnm** [comment]
https://github.com/kobotoolbox/formpack/pull/162 was a fix for this, but we're still having problems:
```
Tino on Mon at 10:54
@John, I just checked on one of my projects and can confirm that column order is off on OCHA. (user nh_iaa) https://kobo.humanitarianresponse.info/#/forms/aYzWjhSCMptCz3uFaLeodS/landing
```

I'll work on fixing this separate but related issue first: https://github.com/kobotoolbox/formpack/issues/163
