### ISSUE TITLE
`list index out of range` in `get_fields_for_versions()`

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/formpack#163]
https://sentry.kbtdev.org/kobo/kpi/issues/7685/ (fails at line 279 `positions[field_name] = (index, len(tmp2d[index]) - 1)`; see `aL5vRzNCNjEDGBuidhWXb5` details at https://www.flowdock.com/app/kobotoolbox/kobo/threads/rlBqKJtKGTSTVTUbBzgQEaGaxwf)

Short example to reproduce this:
```python
from formpack import FormPack

schemas = [
 {'content': {u'schema': u'1',
   u'survey': [{u'label': [u'first but not one'],
     'name': u'first_but_not_one',
     u'type': u'text'},
    {u'label': [u'one'], 'name': u'one', u'type': u'text'},
    {u'label': [u'third'], 'name': u'third', u'type': u'text'}]},
  'version': u'v8wZaeXndV3KpfYkaHLjxC'},
 {'content': {u'schema': u'1',
   u'survey': [{u'label': [u'one'], 'name': u'one', u'type': u'text'}]},
  'version': u'vwjRCb6B7Mje2iRbeW2iyQ'}
]

fp = FormPack(schemas)
fp.get_fields_for_versions(fp.versions.keys())
```

**What's below is a [KPI problem](https://github.com/kobotoolbox/kpi/issues/918) and does not need any code change in this repository:**
Other `list index out of range` errors caused by KPI passing zero deployed versions to formpack (see https://github.com/kobotoolbox/kpi/issues/918):
https://sentry.kbtdev.org/kobo/kpi/issues/7709/ (fails at 256 `for section in versions_desc[0].sections.values():`; no versions were passed in for `a7R8TWUqe26WQCtmBaffaR`?)
https://sentry.kbtdev.org/kobo/kpi/issues/7191/ (fails at 228 `for section in versions[0].sections.values():`; also `a7R8TWUqe26WQCtmBaffaR`)

**Comment by jnm** [comment]
See https://www.flowdock.com/app/kobotoolbox/kobo/threads/rlBqKJtKGTSTVTUbBzgQEaGaxwf

**Comment by jnm** [comment]
Removed critical status since KPI can now run with @noliveleger's patch (see https://github.com/kobotoolbox/kpi/pull/1619)

**Comment by noliveleger** [comment]
it has been merged into master.
Closing this issue
