### ISSUE TITLE
Fall back on XML values for untranslated choices

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/formpack#167]
If the label for a given `lang` is `None`, then the XML value should be used instead. Example of the problem:
https://github.com/kobotoolbox/formpack/blob/34496f7ab6e409cc2c2bd569c61b053be6ef2862/src/formpack/schema/fields.py#L623-L627

Must also check whether other types of fields are affected (only `FormChoiceField` and `FormChoiceFieldWithMultipleSelect` have choices? I think?).

**Comment by joshuaberetta** [comment]
Appears to have been fixed by db2724725490c9402e695a4b0df397846385ba58
