### ISSUE TITLE
`OverflowError: length too large` when exporting CSV

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/formpack#184]
The CSV appears to contain the same things (including the header row) over and over again until its size exceeds 4GB and an `OverflowError` is raised: https://www.flowdock.com/app/kobotoolbox/support/threads/1CWyo_tpVuzFXq3YctIiP_4TLKM

**Comment by noliveleger** [comment]
Closing this issue because it's a `kpi` issue.
