### ISSUE TITLE
download large exported media size

### ISSUE THREAD

**Issue by yabasha** [kobotoolbox/formpack#192]
Hello,

When I download the exported media file i get a corrupted zip file because the exported media file size 1.1 GB, the download works fine until it reaches 1 GB and the transfer stops is there a limit on the download for exported files?

If there is a limit how can I download the exported zip file? or is there ftp access to download the exported file? I tried many download manager but no luck.

Please Advice,

**Comment by jnm** [comment]
The code in this repository doesn't handle media exports, at least not yet anyway :)
There is not a transfer limit on the instances we host on kobotoolbox.org and humanitarianresponse.info. You may consider following the instructions in the "Adding direct hyperlinks to collected media in Excel" section of http://support.kobotoolbox.org/managing-your-project-s-data/data-exports/downloading-photos-and-other-media. You should end up with a column full of URLs that you can download with your favorite download manager.

If you need further assistance, please post at https://community.kobotoolbox.org/.
