### ISSUE TITLE
server error 500 in kobo toolbox 

### ISSUE THREAD

**Issue by jibransohail** [kobotoolbox/formpack#199]
![Screenshot_3](https://user-images.githubusercontent.com/15804773/60216000-5e7e0b80-9882-11e9-88c1-8034162009fe.jpg)

i tried to make change in form n then redeploy it and now i am facing error in reports module of Kobo ,,,
can anybody help me how i can remove this error and can generate my reports

**Comment by jibransohail** [comment]
the main change which i made is in select_multiple **or_other**  that was a major change in the form after that it stop working. i am so much tense please if anybody could help me.

**Comment by noliveleger** [comment]
Not sure it's related to `FormPack`. 
Please visit http://community.kobotoolbox.org . You may get some help for your issue.
