### ISSUE TITLE
`ValueError: unknown type` for newer XLSForm types

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/formpack#212]
Example: `rank`
![image](https://user-images.githubusercontent.com/2085013/77011299-f0aece00-6941-11ea-9fb8-ebe64b04038b.png)
All question types probably need to be included in:
https://github.com/kobotoolbox/formpack/blob/8628d7ee1be74e6a87bb071cd1ac54d002033692/src/formpack/utils/replace_aliases.py#L120-L142
Plus, for exports, they need to be added to:
https://github.com/kobotoolbox/formpack/blob/8628d7ee1be74e6a87bb071cd1ac54d002033692/src/formpack/schema/fields.py#L160-L178

**Comment by jnm** [comment]
Another example `start-geopoint`
https://www.flowdock.com/app/kobotoolbox/support/threads/ceN2y5CEJVJWIGS9hdWKy2iMk-s

**Comment by jnm** [comment]
Another one: `select_one_from_file`
https://github.com/kobotoolbox/kpi/issues/2275

**Comment by jnm** [comment]
for searchability, the export errors are `invalid data_type`, e.g. `invalid data_type: select_one_from_file hohum.csv`
![image](https://user-images.githubusercontent.com/2085013/85341591-89f7fe00-b4b6-11ea-97bc-0bfe73165528.png)

**Comment by joshuaberetta** [comment]
closed by formpack#247

**Comment by joshuaberetta** [comment]
closed by kobotoolbox/formpack#247
