### ISSUE TITLE
Upgrade to pyxform 1.3.4

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/formpack#213]
https://github.com/XLSForm/pyxform/releases/tag/v1.3.4

**Comment by Kalyan-Lama** [comment]
**For referencing record:**

https://www.flowdock.com/app/kobotoolbox/support/threads/YrfuFsbIoMY1bgcLEaDsD1H4hYg

`${last-saved#variable_name}` not functioning in the current version of KoBoToolbox.

**Comment by joshuaberetta** [comment]
Closed by kobotoolbox/formpack#247
