### ISSUE TITLE
Exporting a CSV from a multi-lingual Survey with 'fields_from_all_versions' results in an error "sequence item x: expected str instance, NoneType found"

### ISSUE THREAD

**Issue by MakElblotto** [kobotoolbox/formpack#285]
I'm not sure if this is a KPI issue or a formpack issue. 
A quick search through the issues found this closed issue with a similar error string https://github.com/kobotoolbox/formpack/issues/259 which is what made me suspect the translation changes to the form triggered the error, as explained below.

Invoking the API at endpoint /api/v2/assets/uid/exports with the `fields_from_all_versions` value set to `true` can cause an error with the message
```
"status": "error",
            "messages": {
                "error": "sequence item 9: expected str instance, NoneType found",
                "error_type": "TypeError"
            },
```
when a form is redeployed with more languages/translations.

In this instance, the most significant change that the form had undergone before redeployment was the addition of several more languages/translations, though there are other smaller changes as well.

Although I think it is an unrelated problem, it may be worth mentioning just in case, the form (in both it's original 2 languages, and it's redeployed version with 8) when uploaded shows an extra 'blank' or 'empty' translation which must be deleted from KoboToolbox's form landing page before it can be deployed without error. This extra 'empty' language doesn't seem to appear in ODKCollect, and both versions of the form pass the ODK-Validate tool.

json:
```
$json = @'
{"fields_from_all_versions":"true",
 "group_sep":",",
 "hierarchy_in_labels":"false",
 "include_media_url":"false",
 "lang":"_default",
 "multiple_select":"both",
 "type":"csv"
}
'@
```
The full response from the API endpoint"
```

        {
            "url": "http://kf.kobo.local/api/v2/assets/aV6Y8R6EEkTBkPqGgeArgf/exports/emrGe4dFXRKcDdnTEVHyKb/",
            "status": "error",
            "messages": {
                "error": "sequence item 9: expected str instance, NoneType found",
                "error_type": "TypeError"
            },
            "uid": "emrGe4dFXRKcDdnTEVHyKb",
            "date_created": "2022-02-08T07:06:17.412213Z",
            "last_submission_time": null,
            "result": null,
            "data": {
                "lang": "_default",
                "name": null,
                "type": "csv",
                "source": "http://kf.kobo.local/api/v2/assets/aV6Y8R6EEkTBkPqGgeArgf/?format=json",
                "group_sep": ",",
                "multiple_select": "both",
                "include_media_url": "false",
                "hierarchy_in_labels": "false",
                "processing_time_seconds": 0.188176,
                "fields_from_all_versions": "true"
            }
        }
```

**Comment by joshuaberetta** [comment]
Hi @MakElblotto, thank you for reporting this. There is good chance the issue will be resolved by https://github.com/kobotoolbox/formpack/pull/280 (although it's yet to be in production) and the error message fixed by https://github.com/kobotoolbox/formpack/pull/284. 

Since you are running a local instance, you can use the latest hash from the tip of formpack's master branch in KPI's [requirements.in](https://github.com/kobotoolbox/kpi/blob/master/dependencies/pip/requirements.in#L5) file and then run `make pip_compile` from inside the container.

**Comment by MakElblotto** [comment]
Hi @joshuaberetta, thanks for the information.

When I get the chance, I will do as you suggest and use the latest iteration of formpack to re-test the issue, and then report back if I can determine that it's resolved or still persistent.

**Comment by MakElblotto** [comment]
This issue does appear to be resolved, as I'm unable to replicate it using the latest version.
