### ISSUE TITLE
Data missing from some large exports when include_media_url is True

### ISSUE THREAD

**Issue by joshuaberetta** [kobotoolbox/formpack#302]
On _some_ (not all) large exports with submission counts nearing 30k, the majority of data is missing for submissions after a certain point when `include_media_url` is set to `True`. No data is missing when `False`.

Community report: https://community.kobotoolbox.org/t/data-showing-on-the-kobo-portal-but-not-in-xls-downloaded-file/31640

**Comment by jnm** [comment]
We generally reserve the phrase "data loss" for a situation where data is lost irrevocably, e.g. if the performing such an export somehow caused the server to erase data.

**Comment by jnm** [comment]
I think my #309 does duplicate this issue, but let's track it over there. It will be fixed by #315.
