### ISSUE TITLE
Numeric responses should be saved as numbers in XLS file

### ISSUE THREAD

**Issue by dorey** [kobotoolbox/formpack#44]
Currently all number responses in the Excel export are saved as text. Instead they should be saved as numbers (to allow the user to run calculations without having to manually change the data type each time).

![image](https://cloud.githubusercontent.com/assets/673511/15045554/18abc014-12a9-11e6-93fb-3ef73c0b35e7.png)

**Comment by tinok** [comment]
@ksamuel see updated description above. Interestingly, the _id and _index columns are saved correctly as numbers recognized by Excel.

**Comment by tinok** [comment]
This issue is becoming more important again. Excel is crashing consistently for me when I try to convert a large number of numbers-stored-as-text to numbers. 

@jnm Putting this on your radar.
