### ISSUE TITLE
Include URL of media attachments in exports

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/formpack#47]
For each attachment (video, image, recording, audit.csv, etc.) that was sent with a submission, include the URL to the file in an additional column named `[original_question_name]_URL`.

For example

|name|image|image_URL|
|--|--|--|
|tino|someimage.jpg|https://kc.kobotoolbox.org/media/original?media_file=tinokreutzer/attachments/45c70e9b2cdc44b8b047cfd135542e56/41a86b06-4d1c-4c5c-8b4e-2cf019d30a83/someimage.jpg|

Related to #43 and #46

**Comment by tinok** [comment]
In the CSV and XLS file these can be just saved as text URLs. In the HTML table it should be shown as a clickable hyperlink.

**Comment by dorey** [comment]
The link should be configured as a parameter to the export, because not all links are in the same format. Perhaps the configurable string could look like `"https://server/something{username}/.../{filename}"` so that formpack can call `.format(...)` with the attachment data and context.

**Comment by ksamuel** [comment]
Actually we need an additional layer for that. Right now the export let you control the export general format, but not the detail for each format. So we should have classes to format individual values, and have a generic format() method on fields, which call the currently set formatter object. This way we can have a generic and extensible way of formatting any field while being able to set a default dull formatting for a lot of values.

**Comment by tinok** [comment]
This sounds like a solution for #44, #58, and #59 as well!

**Comment by ksamuel** [comment]
Yes.

**Comment by dorey** [comment]
Connected to #58 and #59

**Comment by tinok** [comment]
@noliveleger I wonder if we could implement this issue now that `download_url` is stored for each `attachment`?

**Comment by noliveleger** [comment]
@tinok, I guess it would be doable assuming the `download_url` property would have always the same name.

**Comment by noliveleger** [comment]
Unfortunately, not now. Maybe some day when the new gallery is released.

**Comment by joshuaberetta** [comment]
Moved to: https://www.notion.so/kobotoolbox/Include-URL-of-media-attachments-in-exports-0babb95ade224d218c82aa36d908ee25
