### ISSUE TITLE
Testing / export issues

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/formpack#56]
- [x] for blank responses in select_multiple questions, don't write `0` and `1` in the split columns (it's a null response and these need to stay empty as well)
- [ ] text and barcode response columns should be formatted as text in Excel (otherwise leading zeros are stripped from e.g. phone numbers, ID numbers)
- [ ] integers are stored as text in Excel, they should be stored as General or Numbers
- [ ] Dates are not recognized in Excel (en_US)
- [ ] the order of columns for split select_multiple questions is not correct: it should be the same order as in the form (right now seems to be random)
- [x] parent groups are duplicated in split GPS columns

original question: `d/G_A/group_qb6pp39/GPS_coordinates`
Expected split question: `d/G_A/group_qb6pp39/GPS_coordinates_latitude`
Current: `d/G_A/group_qb6pp39/_d/G_A/group_qb6pp39/GPS_coordinates_latitude`

- [ ] leading and trailing spaces from Text responses are not included in cells but should be (like in CSV)
- [ ] _id column is missing from export (kc's pk), this may be important to some power users

**Comment by dorey** [comment]
can we rename `_id` to something more explicit? `xform_pk` maybe?

**Comment by tinok** [comment]
Sounds good to me! But it should be a leading underscore to go with the other added meta columns, and I'd say it shouldn't be xform_pk since the xform has a separate number. 

`_submission_pk` ?

**Comment by dorey** [comment]
Ok. I thought it was something that KC was injecting in every row. But looks like it is actually just another field that is passed through from mongo, in which case I think we should keep whatever the key is in mongo. So, passing `_id` through does seem like a good option. Sorry about the confusion

**Comment by tinok** [comment]
Moved all remaining items to separate issues.
