### ISSUE TITLE
text and barcode response columns should be formatted as text in Excel 

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/formpack#58]
(otherwise leading zeros are stripped from e.g. phone numbers, ID numbers)

**Comment by jnm** [comment]
Was this a preemptive issue to keep in mind when fixing #44?

**Comment by tinok** [comment]
@jnm Not quite; my original assumption was that all fields should be stored as numeric (or "General" in Excel), which is especially useful for numeric XML to select_one and for select_multiple questions (which are often coded as 1, 2, 3, 4, etc. in survey design). #44 was to make sure that they are the exception.

**Comment by jnm** [comment]
I think we're largely saying the same thing:

1. **Right now**, as described by #44, "all number responses [and every kind of responses] in the Excel export are saved as text".
2. You want numbers stored as numbers (also #44), not as text.
3. _However,_ some things that look like numbers should be stored as text (this issue).

(2) will be fixed by using the question type in the form definition to determine the Excel cell format, not by saying "hey, that response looks like a number: let's store it in Excel as a 'General'."

I don't understand your comment about "all fields should be stored as numeric." I don't think we ever want a `text` to be stored as "General" in Excel, right? If `select_*` would benefit from being stored as "General" even though it's not a numeric type, then we can add some magic for that if it would really help a lot of people.

**Comment by tinok** [comment]
> I don't understand your comment about "all fields should be stored as numeric." I don't think we ever want a `text` to be stored as "General" in Excel, right? If `select_*` would benefit from being stored as "General" even though it's not a numeric type, then we can add some magic for that if it would really help a lot of people.

I agree, `text` should always be stored as text; though in the kobocat XLS export, text questions are also stored as General (but a number entered is stored as text anyway, which makes me think that the formatting of the column (General) is different from how the value is stored in the XLSX file. See screenshot of kobocat xls export (yellow cell shows numeric response to text question is stored as text): 
![Uploading image.png…]()

> In the end, we need a mapping that specifies the desired Excel cell format ([NB](https://xlsxwriter.readthedocs.io/format.html#set_num_format)) for each question type.

Agreed. On that note, before we forget (general means number / decimal, as in kobocat export)


| question type                   | store data as                            |
|---------------------------------|------------------------------------------|
| integer                         | general                                  |
| decimal                         | general                                  |
| range                           | general                                  |
| text                            | text                                     |
| select_one                      | general                                  |
| select_multiple                 | general                                  |
| select_multiple_from_file       | general                                  |
| select_multiple (split columns) | general                                  |
| rank [options]                  | general                                  |
| note                            | n/a                                      |
| geopoint                        | general                                  |
| geopoint (split columns)        | general                                  |
| geotrace                        | geopoint                                 |
| geoshape                        | general                                  |
| date                            | date (formatted as yyyy-mm-dd?)          |
| time                            | time (formatted as HH:mm:ss?)            |
| dateTime                        | time (formatted as yyyy-mm-dd HH:mm:ss?) |
| image                           |                                          |
| audio                           |                                          |
| background-audio                |                                          |
| video                           |                                          |
| file                            |                                          |
| barcode                         | text                                     |
| calculate                       | text?                                    |
| acknowledge                     |                                          |
| hidden                          |                                          |
| xml-external                    |                                          |
| today                           | date                                     |
| index                           | date (formatted as yyyy-mm-dd?)          |
