### ISSUE TITLE
Sort order of multi select columns in data exports should mirror form order

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/formpack#60]
the order of columns for split select_multiple questions is not correct: it should be the same order as in the form (right now seems to be random). When a select_multiple response wasn't ticked in any submission it should still be included as a blank column in the dataset. Formpack currently excludes it.

See screenshot: 
![image](https://user-images.githubusercontent.com/673511/28624138-234d518e-71e6-11e7-83b7-3d48101de4b5.png)

Expected output would be this (column b follows column a, as in the form design):
![image](https://user-images.githubusercontent.com/673511/28624152-3c8fa778-71e6-11e7-870e-df8cbb88044f.png)

**Comment by ksamuel** [comment]
Is it still the case ?

**Comment by tinok** [comment]
Yes: 

![image](https://cloud.githubusercontent.com/assets/673511/15045349/062af01e-12a8-11e6-9052-554e306bbb06.png)

**Comment by tinok** [comment]
Just to confirm: This bug still persists. The order of the select_multiple responses don't mirror the order of responses in the question. 

When a response wasn't ticked it should still be included in the dataset. Formpack currently excludes it. I've updated this in the bug description.

**Comment by jnm** [comment]
@tinok, I can't reproduce this with a form having a single version on kf.master.kbtdev.org (running the lastest KPI-formpack export code). I used [this form](https://github.com/kobotoolbox/formpack/files/1604632/aPStG8LXkJBiEAM5L6s99v.xlsx), which generated [this export](https://github.com/kobotoolbox/formpack/files/1604633/formpack.60.single.version.-.values.-.2018-01-04-20-15-1.xlsx).

However, I found another bug after changing a single select question to a multi select of the same name. The exploded columns have no headers and a seemingly random order 😭 For the first three submissions below, the question named `multi` was a `select_one`. For the last three, it was a `select_multiple`.

multi |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
option_1 |   |   |   |   |   |   |  
option_2 |   |   |   |   |   |   |  
option_3 |   |   |   |   |   |   |  
Option 1 Option 2 Option 3 Option 4 | 1 | 1 | 1 | 0 | 0 | 1 | 0
Option 1 Option 2 Option 3 Option 4 Option 5 | 1 | 1 | 1 | 0 | 0 | 1 | 1
Option 6 Option 7 | 0 | 0 | 0 | 1 | 1 | 0 | 0

Additionally, labels aren't being shown for `select_one` choices.

**Comment by joshuaberetta** [comment]
This original issue has been resolved and the [additional issue](https://github.com/kobotoolbox/formpack/issues/60#issuecomment-355391734) by @jnm has been filed in kobotoolbox/formpack#151
