### ISSUE TITLE
include instance id number in exports

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/formpack#74]
The `_id` column for each instance is currently included in KC exports and should be included in formpack exports as well. This is important to some power users.

**Comment by ksamuel** [comment]
_id is now exposed, I can see it in HTM and csv, but on big xls files I can't on my machine with libre office. Do you have the same issue for reports such as https://kc.kbtdev.org/uganda_14/reports/uga_14_v6/export/ ?

**Comment by tinok** [comment]
@ksamuel I'm able to open [this XLS file](https://kc.kbtdev.org/drc_14/reports/drcpoll06v2/export.xlsx) in Excel and LibreOffice, and it includes the _id column, so I think we're good.

**Comment by ksamuel** [comment]
Ok, apparently my version of LO is limited to 1024 columns: https://wiki.documentfoundation.org/Faq/Calc/022

This explains the id, which is at the end, in truncated for me on huge reports. Closing.
