### ISSUE TITLE
Group labels are included when set to None

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/formpack#87]
Test with [this project](https://kc.kbtdev.org/uganda_14/reports/ariEXFiJVt8nSx7CXn9XZE/export/). 

When exporting with [export.xlsx?lang=_default&group_sep=%2F&hierarchy_in_labels=None](https://kc.kbtdev.org/uganda_14/reports/ariEXFiJVt8nSx7CXn9XZE/export.xlsx?lang=_default&group_sep=%2F&hierarchy_in_labels=None) there should be no group headers included. 

Instead: group headers are included for both regular groups and repeat groups. 

![image](https://cloud.githubusercontent.com/assets/673511/15344332/0668bc8e-1c74-11e6-8ef0-d28467715a93.png)

![image](https://cloud.githubusercontent.com/assets/673511/15344337/0ecf1f30-1c74-11e6-8002-26bd2ec7d785.png)

**Comment by ksamuel** [comment]
I don't understand in which situation do you get "None" here ? Do you add it manually, or does the tool give you this url ?

**Comment by jnm** [comment]
Cannot reproduce any longer on kf.master.kbtdev.org with latest KPI-formpack exports
