### ISSUE TITLE
Incomplete export

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/formpack#88]
In at least one project, formpack data exports show almost all the data columns as blank, except the first three columns. 

![image](https://cloud.githubusercontent.com/assets/673511/17945870/a7d5b530-6a13-11e6-81bf-8933e506085d.png)

See user-specific details [here](https://www.flowdock.com/app/kobotoolbox/kobo/threads/udxY93tUkKQQAkUayDFdCS0uGR4).

**Comment by tinok** [comment]
Duplicate or Related to kobotoolbox/kpi#1056 and kobotoolbox/kpi#882?

**Comment by jnm** [comment]
@tinok, it might be a duplicate of https://github.com/kobotoolbox/kpi/issues/1348. I say "might" because most, but not all, of the question names in this form contain dots.

**Comment by jnm** [comment]
Closing; other issues with this form are now tracked at https://github.com/kobotoolbox/formpack/issues/139
